### ISSUE TITLE
changing LD_LIBRARY_PATH can brokeOS python function

### ISSUE THREAD

**Issue by Kaiz3rTool** [boberfly/GafferCycles#17]
on our system (centos), because of our remote connexion tool, we cant allow any change on OS system variable
changing LD_LIBRARY_PATH have broke all python (even yum) run by centos 

potential solution :
create a gaffer specific variable like GFR_LD_LIBRARY_PATH

**Comment by boberfly** [comment]
Hi @Kaiz3rTool 
Have you tried something like:
`export LD_LIBRARY_PATH=/some/path/to/custom/libs:$LD_LIBRARY_PATH` to merge multiple paths instead of overriding it?

Also I don't recall needing to override it for GafferCycles, are you looking in the standalone Gaffer launcher script? There can't be a custom one because it is a Linux-specific environment variable to find custom libraries outside of system ones.

**Comment by Kaiz3rTool** [comment]
I haven't tried it for now, I was planning to test it before I realize that the problem may come from me, as I have setup compile variable permanently even if I use the compiled one, so it seems I've made a useless (and buggy) setup

**Comment by boberfly** [comment]
All good, yeah it sounded a bit strange... :)
