### ISSUE TITLE
shader assignment plug dragging direction affect result (black 

### ISSUE THREAD

**Issue by edmondeng** [boberfly/GafferCycles#24]
![screenshot](https://user-images.githubusercontent.com/4751948/67457906-c0a90c00-f5e9-11e9-955f-8914bfdfb00a.jpg)

In 0.10.2 i can consistently get black solid no shading when plugging from the shader assignemnt to a shader however it works fine dragging to the shader assignment from a shader.

e

**Comment by edmondeng** [comment]
WARNING : IECoreCycles::ShaderNetworkAlgo : Couldn't find socket output "" on shaderNode "shader:d969474247b8c6a68b0728d7a0a8049f:add_closure"

WARNING : IECoreCycles::ShaderNetworkAlgo : Couldn't find socket output "" on shaderNode "shader:72e5800843fa6a9f340c30b0b34551da:principled_bsdf3"

These are 2 warnings when dragging from shader assignment to the add closure node and a principled with a bsdf output. 

e

**Comment by boberfly** [comment]
I wonder if I can just summon @johnhaddon by putting his name here. This looks like a very old issue that John fixed long ago for me so that ShaderNetwork specifies the specific output parameter name. Maybe it is a detail I need to supply though for when connections are done from ShaderAssignment to a CyclesShader but I am not sure...

**Comment by johnhaddon** [comment]
Hey Edmond, can you run the following for each of your connection directions (the green and the red)?

```print root["ShaderAssignment1"]["shader"].getInput().fullName()```?

Let us know what you get...

**Comment by boberfly** [comment]
It might be an "*I done goofed*" here and just need to re-instate this blindly copy-pasta'd code I found once in ArnoldShader.cpp

https://github.com/boberfly/GafferCycles/blob/master/src/GafferCycles/CyclesShader.cpp#L104

**Comment by alexnardini** [comment]
I did read “pasta” somewhere so, I’m in !

**Comment by edmondeng** [comment]
I will be able to do John’s print out when I get the scene working again. My driver might have reset or something as a fully working scene won’t open

**Comment by boberfly** [comment]
I didn't do a print but I have noticed if I use a cclOutput node and connect a surface or volume connection to this, it shows me the string name of the incoming connection, and it does come up as like `principled_surface.out` incorrectly or `principled_surface.out.BSDF` correctly.

**Comment by edmondeng** [comment]
FYI,  @johnhaddon  either connection order produces same output. But seems like Alex knows what's goin on.


print root["ShaderAssignment1"]["shader"].getInput().fullName()
gui.scripts.ScriptNode.principled_bsdf.out.BSDF
print root["ShaderAssignment1"]["shader"].getInput().fullName()
gui.scripts.ScriptNode.principled_bsdf.out.BSDF

**Comment by boberfly** [comment]
Big massive hint here. If I drag the shader assignment onto the node itself it'll plug to the .out plug, but if you highlight the explicit nodule with BSDF on it, it works. See screenshots:
![bad_connect](https://user-images.githubusercontent.com/5601445/68570958-b030c800-0416-11ea-99db-ea9e280c5b43.png)
![good_connect](https://user-images.githubusercontent.com/5601445/68570960-b0c95e80-0416-11ea-9609-e1671625dfb0.png)
Is there some metadata I need to set to prevent these connections @johnhaddon ?

Cheers

**Comment by johnhaddon** [comment]
> Big massive hint here. If I drag the shader assignment onto the node itself it'll plug to the .out plug, but if you highlight the explicit nodule with BSDF on it, it works.

Ah! I think I see what is happening. Could you see if this commit fixes it for you?

https://github.com/johnhaddon/gaffer/commit/8c4fec02d1a1d262321d7607b1c44b2849ca5fa5

**Comment by boberfly** [comment]
Hey @johnhaddon 
I haven't tried this just yet but I had another thought after @murraystevenson gave me a patch for a cycles shader ball, does a default .out need to be established when clicking on a given shader node for it to be able to view as well? I haven't had a close look to this but he did note it and it isn't working right now.

**Comment by johnhaddon** [comment]
The Viewer is the thing that decides what to connect into the ShaderView, and it connects the first plug that `ShaderView["in"]` will accept, which I believe will be `CyclesShader.out` in this case. You may be able to work around this by making `CyclesShaderBall.acceptsInput()` reject that connection - maybe that's what Murray's patch does?

I'd like to step back a bit and fill a gap in my knowledge : why do you need an `out.BSDF` connection rather than just `out`? I think this is the first such example among all the renderers we've looked at. Are there other valid `out.foo` connections that could be made into a ShaderAssignment?

**Comment by boberfly** [comment]
For uber-shaders like the principled_bsdf there is only one called BSDF but some shaders have multiple outputs and I need to know the particular name for Cycles to know what to connect to, like some are named BSSDF like the subsurface closure for example. Other shaders have multiple out connections as well.

**Comment by johnhaddon** [comment]
Is there ever a time when you'd want to assign the BSSDF from one shader _as well as_ the BSDF from another? Or is it fine that an upstream assignment from BSSDF would be overridden by a downstream assignment from BSDF?

**Comment by boberfly** [comment]
Hmm, I would say you'd replace the ccl:surface attribute to the object with one or the other but not both. You can use a mix shader to combine multiple closures with a mixing weight value and connecting that up to the ccl:surface attribute, so I am guessing the latter if I understand correctly.

Having a think about it, perhaps just not accepting .out as a valid connection and always defaulting to the first out in the array would solve most all the potential issues, and if there's multiple outputs needing to be explicitly viewed I can imagine just using some emission/constant node on the end that is connected to the output that the user wants to view is a valid compromise.

**Comment by johnhaddon** [comment]
> Hmm, I would say you'd replace the ccl:surface attribute to the object with one or the other but not both.

Cool. I just wanted to check that the way Gaffer is doing things (minus the problem we're talking about) fits Cycles reasonably well, and it seems like it does, so that's good.

> Having a think about it, perhaps just not accepting .out as a valid connection and always defaulting to the first out in the array would solve most all the potential issues

For other shader types we do currently need to accept `.out` as an input - for instance, ArnoldShaders always have a single output, which we represent as `.out` rather than `.out.foo`. I think this was probably a mistake and we should always have things nested under `.out`, but I'd rather not have to think about how to manage that transition right now.

I think we can probably achieve what we need by a slight modification to ShaderPlug though (this is the input type on the ShaderAssignment). See here :

https://github.com/GafferHQ/gaffer/blob/master/src/GafferScene/ShaderPlug.cpp#L73

I think we can add a caveat to the `plug == shader->outPlug()` part whereby we only allow this top-level connection if `shader->outPlug()->typeId() != PlugTypeId`. This would reject situations where `.out` is a container for shader outputs rather than a shader output itself.

**Comment by boberfly** [comment]
Hey @johnhaddon 
Just reading your updated reply now. I did a sneaky fix on the ShaderNetwork conversion code which makes the ShaderBall preview work also:
https://github.com/boberfly/GafferCycles/blob/master/src/GafferCycles/IECoreCyclesPreview/ShaderNetworkAlgo.cpp#L436
There might be potential issues with this in-future, but for the most part it is working...

**Comment by boberfly** [comment]
Working right now, feel free to re-open if it's not. Connections can still go onto the node itself so it might be a gotcha if you are not wanting to use the first out plug.
