### ISSUE TITLE
rendering scene from alembic can crash because of unknown normal

### ISSUE THREAD

**Issue by Kaiz3rTool** [boberfly/GafferCycles#28]
Hi
I tried a new scene from maya
when I render it in intereactive mode, the image compute but the terminal return this 

`WARNING : MeshAlgo : Variable "N" has unsupported interpolation type - not generating normals.`

but the image looks as it should
with the same settings, rendering the image with cycles render node wont render anything then crash gaffer with both local dispatcher and deadline

here is a basic scene to reproduce the problem
cheers
[pixels13.zip](https://github.com/boberfly/GafferCycles/files/3783945/pixels13.zip)

**Comment by boberfly** [comment]
Hey @Kaiz3rTool 

I couldn't find a way for Cycles to support FaceVarying normals so I put that warning in and do an early-exist, most likely Cycles generates a re-normalised per-vertex normal itself I'd say. If you want to remove the warning, running a MeshType node which re-generates normals can do the trick, or a ResamplePrimitiveVariables node and change N to vertex.

The crash that you're getting sounds like it could be because you have interactive and batch AOVs in the same graph. For now can you split the graph so that the outputs are specified separately for batch render and interactive? I will get around to fixing this and you just reminded me to fix that again, but try that for now.

Cheers!

**Comment by Kaiz3rTool** [comment]
hi,
thanks, the meshType, it does the trick
I have tried to separate batch / interactive and also to only use a single beauty output, I still have the same issue with no image writed on disk 
the server stay at 100% CPU, as usual for rendering task, but nothing goes out and the log doesn't return anything

**Comment by boberfly** [comment]
Hey @Kaiz3rTool this was another issue with batch mode, I can verify that batch mode is working great for me in https://github.com/boberfly/GafferCycles/releases/tag/0.13.0 so I'll close this.
