### ISSUE TITLE
Build fails on Linux Mint 19.3

### ISSUE THREAD

**Issue by amsaid1989** [boberfly/GafferCycles#52]
I am trying to build the latest release of GafferCycles (0.18.2) with all the dependencies. I cloned the repo, built all the dependencies before the actual build. When I get to the actual build, I get the error in the following paste bin: https://pastebin.com/EnTNyYDq

Any ideas what might be causing the issue?

**Comment by boberfly** [comment]
Hi @amsaid1989 

Looks like some environment variables are not being set so it cannot find the `oslc` compiler.
```
export GAFFER_ROOT=<gaffer install path>
export GAFFERCYCLES=<install destination>
export LD_LIBRARY_PATH=$GAFFER_ROOT/lib
```
The notable ones are setting the `$GAFFER_ROOT` to point to where gaffer is installed (this contains the oslc compiler) and `$LD_LIBRARY_PATH` so that the boost library can be found which is one of the dependencies of `oslc` and a part of Gaffer itself.

Hope this helps

**Comment by amsaid1989** [comment]
That is very strange. I had all these variables set, but I will try it again, maybe I had a typo in one of them or something. Thanks for the help, Alex. I will test and update you.

**Comment by boberfly** [comment]
All good @amsaid1989 ? It's a bit tricky to build, feel free to re-open and I can assist.

**Comment by amsaid1989** [comment]
Really sorry, Alex. Got really busy in the past couple of months and haven't managed to retry building it. Once I have some time, I will try again and reopen the issue if I am still having problems.
